# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

# file-version: 1.0

version: 2

updates:
  - package-ecosystem: "composer"

    directory: "/"

    schedule:
      interval: "weekly"
      day: "saturday"
      time: "04:00"
      timezone: "Europe/Berlin"

    open-pull-requests-limit: 10

    reviewers:
      - "mimmi20"

    assignees:
      - "mimmi20"

    labels:
      - "dependencies"

    versioning-strategy: "increase"

    target-branch: "master"

    commit-message:
      include: "scope"
      prefix: "composer (master)"

    ignore:
      - dependency-name: "elasticsearch/elasticsearch"
      - dependency-name: "predis/predis"
      - dependency-name: "psr/container"

    # Disable rebasing for all pull requests
    rebase-strategy: "disabled"

  - package-ecosystem: "github-actions"

    directory: "/"

    schedule:
      interval: "weekly"
      day: "saturday"
      time: "04:00"
      timezone: "Europe/Berlin"

    open-pull-requests-limit: 10

    reviewers:
      - "mimmi20"

    assignees:
      - "mimmi20"

    labels:
      - "dependencies"

    target-branch: "master"

    commit-message:
      prefix: "github-actions (master)"

    ignore:
      - dependency-name: "mimmi20/ci"

    # Disable rebasing for all pull requests
    rebase-strategy: "disabled"

  - package-ecosystem: "composer"

    directory: "/"

    schedule:
      interval: "weekly"
      day: "saturday"
      time: "04:00"
      timezone: "Europe/Berlin"

    open-pull-requests-limit: 10

    reviewers:
      - "mimmi20"

    assignees:
      - "mimmi20"

    labels:
      - "dependencies"

    versioning-strategy: "increase"

    target-branch: "4.x"

    commit-message:
      include: "scope"
      prefix: "composer (4.x)"

    ignore:
      - dependency-name: "elasticsearch/elasticsearch"
      - dependency-name: "laminas/laminas-servicemanager"
      - dependency-name: "predis/predis"
      - dependency-name: "psr/container"

    # Disable rebasing for all pull requests
    rebase-strategy: "disabled"

  - package-ecosystem: "github-actions"

    directory: "/"

    schedule:
      interval: "weekly"
      day: "saturday"
      time: "04:00"
      timezone: "Europe/Berlin"

    open-pull-requests-limit: 10

    reviewers:
      - "mimmi20"

    assignees:
      - "mimmi20"

    labels:
      - "dependencies"

    target-branch: "4.x"

    commit-message:
      prefix: "github-actions (4.x)"

    ignore:
      - dependency-name: "mimmi20/ci"

    # Disable rebasing for all pull requests
    rebase-strategy: "disabled"
